services:
  dw_scheduler:
    image: bymoxb/dw-scheduler:latest
    container_name: dw-scheduler
    restart: unless-stopped
    environment:
      - TZ=${TZ}
      - DATABASE_URL=${DATABASE_URL}
      - MAIL_PORT=${MAIL_PORT}
      - MAIL_HOST=${MAIL_HOST}
      - MAIL_USER=${MAIL_USER}
      - MAIL_PASSWORD=${MAIL_PASSWORD}
      - MAIL_FROM=${MAIL_FROM}
      - MAIL_TO=${MAIL_TO}
      - DW_EXPIRATION_THRESHOLD=${DW_EXPIRATION_THRESHOLD}
